"""Research memory + belief updates. Institutional memory of successes and failures."""
from __future__ import annotations

import json
import logging
from pathlib import Path

from quant_loop_trader import data as _data
from quant_loop_trader.data import migrate_db

logger = logging.getLogger(__name__)


def _con(db_path=None):
    migrate_db(db_path)
    import duckdb as _duckdb
    return _duckdb.connect(str(Path(db_path or _data.DB_PATH)))


def search_memory(query: str, memory_type: str | None = None,
                  ticker: str | None = None, horizon: int | None = None) -> list[dict]:
    """Search past research by keyword, optionally scoped to one evidence family.

    Historical rows predate market-scoped provenance and were generated by the
    SPY-only system. They remain valid SPY memory, but are never admitted into a
    BTCUSD search. New rows always persist ticker + horizon explicitly.
    """
    con = _con()
    sql = "SELECT * FROM research_memory WHERE authoritative AND (hypothesis ILIKE ? OR lesson ILIKE ?)"
    params = [f"%{query}%", f"%{query}%"]
    if memory_type:
        sql += " AND memory_type = ?"
        params.append(memory_type)
    if ticker:
        ticker_u = ticker.upper()
        if ticker_u == "SPY":
            sql += (
                " AND (upper(json_extract_string(provenance_json, '$.ticker')) = ? "
                "OR json_extract_string(provenance_json, '$.ticker') IS NULL)"
            )
        else:
            sql += " AND upper(json_extract_string(provenance_json, '$.ticker')) = ?"
        params.append(ticker_u)
    if horizon is not None:
        if ticker and ticker.upper() == "SPY":
            sql += (
                " AND (CAST(json_extract(provenance_json, '$.horizon') AS INTEGER) = ? "
                "OR json_extract(provenance_json, '$.horizon') IS NULL)"
            )
        else:
            sql += " AND CAST(json_extract(provenance_json, '$.horizon') AS INTEGER) = ?"
        params.append(int(horizon))
    sql += " ORDER BY created_at DESC"
    cur = con.execute(sql, params)
    cols = [d[0] for d in cur.description]
    rows = cur.fetchall()
    con.close()
    return [dict(zip(cols, r)) for r in rows]


def record_outcome(report: dict) -> list[str]:
    """Store the research-screen outcome; final confirmation belongs to holdout."""
    decision = report["decision"]
    exp_id = report["experiment_id"]
    hypothesis = report["hypothesis"]
    cfg = report.get("config") or {}
    ticker = cfg.get("ticker")
    horizon = cfg.get("horizon")

    if decision == "KEEP":
        # Keep the legacy memory_type for correction/confirmation machinery, but
        # do not claim hidden-holdout success or increase belief before validation.
        memory_type = "success"
        lesson = (
            f"Provisional KEEP: {hypothesis} Passed the research split and "
            "predeclared screen; pending independent validation and hidden holdout."
        )
        confidence = prior_confidence(hypothesis, ticker=ticker, horizon=horizon)
    elif decision == "IMPROVE":
        memory_type = "partial"
        lesson = "Partial: accuracy improved but Sharpe degraded. Refine risk control before retest."
        confidence = prior_confidence(hypothesis, ticker=ticker, horizon=horizon)
    else:
        memory_type = "failure"
        lesson = (
            f"Rejected: {report['failure_condition']} Vol-interaction features "
            "did not change predictions materially."
        )
        confidence = max(
            0.05,
            prior_confidence(hypothesis, ticker=ticker, horizon=horizon) - 0.2,
        )

    autopsy = report.get("error_analysis", {})
    conditions = json.dumps({k: v for k, v in autopsy.items() if k.startswith("regime")})
    memory_id = f"mem_{exp_id}_{memory_type}"
    provenance = json.dumps({
        "branch": report.get("research_branch"),
        "creator": report.get("creator_agent"),
        "ticker": ticker,
        "horizon": horizon,
    })
    con = _con()
    con.execute(
        "INSERT OR REPLACE INTO research_memory VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'v1', current_timestamp, TRUE)",
        [
            memory_id,
            exp_id,
            memory_type,
            hypothesis,
            report.get("economic_reasoning"),
            decision,
            lesson,
            conditions,
            json.dumps({
                "metrics": report.get("improved_metrics", {}),
                "delta_acc": report.get("improvement_delta_accuracy"),
            }),
            confidence,
            provenance,
        ],
    )

    knowledge_id = f"mem_{exp_id}_knowledge"
    con.execute(
        "INSERT OR REPLACE INTO research_memory VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'v1', current_timestamp, TRUE)",
        [
            knowledge_id,
            exp_id,
            "model_knowledge",
            f"Baseline regime performance for {ticker} {horizon}d",
            None,
            decision,
            (
                f"Autopsy: {autopsy.get('overall_accuracy', 'n/a')} overall accuracy "
                f"across vol regimes; false_positive_rate={autopsy.get('false_positive_rate')}"
            ),
            conditions,
            json.dumps(autopsy),
            0.6,
            provenance,
        ],
    )
    con.close()
    logger.info(json.dumps({
        "event": "memory_recorded",
        "memory_id": memory_id,
        "confidence": confidence,
        "ticker": ticker,
        "horizon": horizon,
    }))
    return [memory_id, knowledge_id]


def prior_confidence(hypothesis: str, ticker: str | None = None,
                     horizon: int | None = None) -> float:
    """Current belief in a hypothesis from accumulated comparable evidence."""
    rows = search_memory(hypothesis[:60], ticker=ticker, horizon=horizon)
    if not rows:
        return 0.5
    return float(rows[0]["confidence"])


def duplicate_risk(hypothesis: str, max_rejects: int = 3,
                   ticker: str | None = None, horizon: int | None = None) -> dict:
    """Flag repeated failures only inside the same market/horizon evidence family."""
    fails = search_memory(
        hypothesis[:60], memory_type="failure", ticker=ticker, horizon=horizon
    )
    return {"similar_failures": len(fails), "should_warn": len(fails) >= max_rejects}


def register_features(feature_defs: list[dict]) -> None:
    """Idempotent feature registration."""
    con = _con()
    for f in feature_defs:
        con.execute(
            "INSERT OR REPLACE INTO feature_registry VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 'v1', current_timestamp)",
            [
                f["feature_id"],
                f["formula"],
                f.get("creator", "feature_engineer_v0"),
                f.get("data_dependencies", "daily OHLCV"),
                f.get("available_time_logic", "shift(1): uses data up to t-1"),
                f.get("validation_status", "validated"),
                "{}",
                f.get("failure_conditions", ""),
                "{}",
            ],
        )
    con.close()


def register_model(model: dict) -> None:
    """Idempotent model registration."""
    con = _con()
    con.execute(
        "INSERT OR REPLACE INTO model_registry VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'v1', current_timestamp)",
        [
            model["model_id"],
            model.get("parent_model_id"),
            model["training_data_version"],
            model["feature_version"],
            model.get("parameters_json", "{}"),
            model.get("performance_history_json", "{}"),
            model.get("failure_modes", ""),
            model.get("research_lineage", ""),
            model.get("status", "candidate"),
            "{}",
        ],
    )
    con.close()
